version: '3'

services:
  pubsub-emulator:
    image: 'gcr.io/google.com/cloudsdktool/cloud-sdk:396.0.0-emulators'
    ports:
      - '8085:8085'
    command: [
      'gcloud', 'beta', 'emulators', 'pubsub', 'start', '--project=test-project', '--host-port=0.0.0.0:8085'
    ]
